# source: https://codeburst.io/tool-your-django-project-pre-commit-hooks-e1799d84551f

default_language_version:
  # default language version for each language
  python: python3.9
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.3.0
    hooks:
      - id: commitlint
        stages: [ commit-msg ]
        additional_dependencies: ['@commitlint/config-conventional']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      # See https://pre-commit.com/hooks.html for more hooks
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # black (ignored in flake)
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  # lint and complexity
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [
            "flake8-bugbear",
            "flake8-comprehensions",
            "flake8-mutable",
            "flake8-print",
            "flake8-simplify",
        ]
  - repo: local
    hooks:
      - id: django-test
        name: django-test
        entry: python runtests.py --noinput
        always_run: true
        pass_filenames: false
        language: system
